#!/bin/sh
HERE=$(dirname "$0")
$HERE/import-feeds.py
$HERE/render.py $HERE/templates/config.ini > $HERE/../iron-blogger-planet/config.ini
$HERE/update-participants.py

# cp "$HERE/bloggers.yml" /mit/nelhage/web_scripts/iron-blogger/
# chmod 777 bloggers.yml
